# Generated by Django 6.0.4 on 2026-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcels',
            name='tracking_number',
            field=models.CharField(default='GN21323', max_length=100),
        ),
    ]
