# Generated by Django 6.0.4 on 2026-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parcels_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
