# Generated by Django 6.0.4 on 2026-04-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_parcels_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcels',
            name='status',
            field=models.IntegerField(choices=[(1, 'Registered'), (2, 'Send'), (3, 'Received')], default=1),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
